name: ServiceNow GitHub Actions CI/CD workflow

on:
  push:
    branches:
      - master
      - development

workflow_dispatch:
  inputs:
    runATF:
      description: "To run the ATF test cases and generate report"
      required: true
      default: 'false'
jobs:
  Git-checkout:
    name: Git-checkout
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Git-checkout Stage
        run: echo "Pull code from GitHub"
        
 
