
name: ServiceNow GitHub Actions CI/CD workflow

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:
    inputs:
      runATF:
        description: "To run the ATF test cases and generate report"
        required: true
        default: 'false'

jobs:
  Git-checkout:
    name: Git Checkout
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Git-checkout Stage
        run: echo "Pull code from GitHub"

  Automationtest:
    if: ${{ github.event.inputs.runATF == 'true' }}
    name: Automation Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run ATF Tests
        uses: ServiceNow/sncicd-tests-run@2.0.0
        with:
          browserName: chrome
          osName: windows
          testSuiteSysId: bde6d5241b421e107ba2ec64604bcb5e
          testSuiteName: Phone Number Validation
            echo "$output" > atf-test-results.json
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowInstallInstance: ${{ secrets.NOW_INSTALL_INSTANCE }}

      - name: Save Test Results to Repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add atf-test-results.json
          git commit -m "Save ATF test results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      
